# meta_agents/agent_generator_agent.py

from openai import OpenAI
from utils.logger_config import get_logger
import os
import re

logger = get_logger("AgentGeneratorAgent")

class AgentGeneratorAgent:
    def __init__(self):
        if not os.getenv("OPENAI_API_KEY"):
            raise ValueError("OPENAI_API_KEY environment variable not set.")
        self.client = OpenAI()

    def generate_agent_code(self, agent_name: str, agent_description: str) -> str:
        """Generates the full Python code for a specific agent based on its description."""
        logger.info(f"Generating code for agent: {agent_name}")

        system_prompt = f"""
        You are an elite Python software architect. Your task is to write the complete, production-ready, and flawless Python code for a single agent class based on the provided specifications.

        **AGENT TO GENERATE:**
        - **Agent Name:** `{agent_name}`
        - **Description:** `{agent_description}`

        **ABSOLUTE, UNBREAKABLE RULES OF CODE GENERATION:**
        1.  **RAW CODE ONLY**: Your entire response MUST be only raw Python code. Do NOT include any conversational text, explanations, notes, or markdown formatting like ```python. Your response must start directly with the first import statement (e.g., `import os`).
        2.  **STRICT SIGNATURES**:
            - The constructor MUST be exactly `def __init__(self):`.
            - The main method MUST be exactly `def run(self, inputs: dict, status_ui=None):`.
        3.  **MODERN OPENAI API (v1.x or higher)**:
            - You MUST use `from openai import OpenAI`.
            - You MUST use `self.client.chat.completions.create(...)`.
            - The `create` method MUST use a `messages` list (e.g., `messages=[{{"role": "user", "content": ...}}]`). DO NOT use the `prompt` argument.
            - You MUST parse the response with dot notation (e.g., `response.choices[0].message.content`).
        4.  **LOGIC FOR `CodeGeneratorAgent`**: If you are generating the `CodeGeneratorAgent`, its purpose is to create the code for the final user application. It MUST be instructed to call the OpenAI API with `response_format={{"type": "json_object"}}`. The JSON it asks for MUST have a `project_name` (string) and a `files` key, where `files` is a list of dictionaries, each with a `name` (e.g., "app.py") and `content` (the full code for that file). The agent's code must then loop through this `files` list and write each file to disk. THIS IS THE MOST IMPORTANT RULE.
        5.  **LOGIC FOR `CodeReviewAndHealingAgent`**: If you are generating the `CodeReviewAndHealingAgent`, it must test the application generated by the `CodeGeneratorAgent`. It must run the app in a subprocess, detect crashes, and send the broken code along with the `stderr` traceback to the AI for fixing. It must expect a JSON response containing the corrected files.

        Generate the code now, following all rules without exception. A failure to follow these rules will break the entire autonomous system.
        """
        
        try:
            response = self.client.chat.completions.create(
                model="gpt-4-turbo",
                messages=[
                    {"role": "system", "content": system_prompt}
                ]
            )
            raw_code = response.choices[0].message.content
            
            # This pattern finds a python code block and extracts its content.
            match = re.search(r"```python\s*([\s\S]+?)\s*```", raw_code)
            if match:
                clean_code = match.group(1).strip()
            else:
                clean_code = raw_code.strip()
            
            return clean_code

        except Exception as e:
            logger.error(f"Failed to generate code for agent {agent_name}: {e}", exc_info=True)
            raise ValueError(f"AgentGeneratorAgent failed to generate code. Error: {e}")
